export const FILMS_ACTION_TYPES = Object.freeze({
    SET_FILMS: 'SET_FILMS',
    SET_TOTAL_PAGES: 'SET_TOTAL_PAGES',
    SET_LOADING: 'SET_LOADING'
});

export const OPTIONS_ACTIONS_TYPES = Object.freeze({
    SET_GENRES: 'SET_GENRES',
    SET_USER_SCORE: 'SET_USER_SCORE',
    SET_RELEASE_DATE_FROM: 'SET_RELEASE_DATE_FROM',
    SET_RELEASE_DATE_TO: 'SET_RELEASE_DATE_TO',
    SET_PAGE: 'SET_PAGE',
    CLEAR_OPTIONS: 'CLEAR_OPTIONS'
});

export const ABOUT_ACTIONS_TYPES = Object.freeze({
    SET_ABOUT_INFO: 'SET_ABOUT_INFO',
    CLEAR_ABOUT_INFO: 'CLEAR'
});

export const SECTIONS_ACTIONS_TYPES = Object.freeze({
    SET_FILMS_SECTION: 'SET_FILMS_SECTION',
    SET_FAVOURITE_SECTION: 'SET_FAVOURITE_SECTION',
    SET_SEARCH_SECTION: 'SET_SEARCH_SECTION'
});

export const FAVOURITE_ACTIONS_TYPES = Object.freeze({
    SET_FAVOURITE: 'SET_FAVOURITE'
});

export const GENRES_ACTIONS_TYPES = Object.freeze({
    SET_RECEIVED_GENRES: 'SET_RECEIVED_GENRES'
});
